# 使用的nodejs版本
node_js: stable

# 仓库的分支
branches:
  only:
  - dev

# 执行isntall前需要执行的命令
before_install:
# 配置解密信息
 - openssl aes-256-cbc -K $encrypted_d3e7e74a3f55_key -iv $encrypted_d3e7e74a3f55_iv -in .travis/id_rsa_github.enc -out ~/.ssh/id_rsa_github -d

# 改变文件权限
 - chmod 600 ~/.ssh/id_rsa_github

# 配置 ssh
 - eval $(ssh-agent)
 - ssh-add ~/.ssh/id_rsa_github
 - cp .travis/ssh_config ~/.ssh/config

# 配置git 的个人信息
 - git config --global user.name 'sunyinjie'
 - git config --global user.email sunyinjie@gmail.com

# 执行install
install:
 - npm install hexo-cli -g
 - npm install
 - npm install hexo-generator-index-pin-top --save

# 执行命令脚本
script:
 - hexo clean
 - hexo g -d
